POST http://localhost:3000/users
Content-Type: application/json


{
    "firstName": "Mark",
    "lastName": "Doe",
    "email": "mark@gmail.com",
    "password": "Pass123!!!"
}

POST http://localhost:3000/users/create-many
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsImVtYWlsIjoibWFya0BnbWFpbC5jb20iLCJpYXQiOjE3NzI2MjkzNzksImV4cCI6MTc3MjYzMjk3OSwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.MaXK4_euvGnHQulzDnSF0Z8_HsBfknldAkB5QpnT6XM
{
    "users": [
    {
    "firstName": "Mark",
    "lastName": "Doe",
    "email": "mark@gmail.com",
    "password": "Pass123!!!"
},
{
    "firstName": "Diana",
    "lastName": "Doe",
    "email": "diana@gmail.com",
    "password": "Pass123!!!"
}
    ]
   
}
