POST http://localhost:3000/auth/refresh-tokens
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsImlhdCI6MTc3MjcyNzY2NiwiZXhwIjoxNzcyODE0MDY2LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.S_wjDpyX4yF7KRk_xImDLVG75DtP7VJAV_jgFS8GPZ8"
}

