POST http://localhost:3000/tags
Content-Type: application/json
Authorization: Bearer ACCESS TOKEN REQUIRED


{
    "name": "tailwind",
    "slug": "tailwind",
    "description": "All posts typescript"
    
}